# Generated by Django 5.2.5 on 2025-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('menu', 'Онлайн меню'), ('shop', 'Інтернет-магазин'), ('booking', 'Система запису')], max_length=20),
        ),
    ]
