# Generated by Django 5.2.5 on 2025-10-06 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='prev_menu_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='prev_qr_scans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='prev_total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='prev_total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistics',
            name='prev_total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Page Visit'), ('qr_scan', 'QR Code Scan'), ('menu_view', 'Menu View'), ('item_view', 'Item View'), ('booking', 'Booking Created'), ('order', 'Order Placed')], max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='businesses.business')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business', 'event_type', 'timestamp'], name='businesses__busines_83ad4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('qr_scans', models.PositiveIntegerField(default=0)),
                ('menu_views', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'Daily statistics',
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
